apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cookbook-deployment
  namespace: jenkinsworld
spec:
  selector:
    matchLabels:
      app: cookbook
  replicas: 2 
  template:
    metadata:
      labels:
        app: cookbook
    spec:
      containers:
      - name: cookbook
        image: seematech/cookbook:25
        imagePullPolicy: Always
        ports:
           - containerPort: 8080
      imagePullSecrets:
           - name: $KUBERNETES_SECRET_NAME
           - name: regcred

   
---

kind: Service
apiVersion: extensions/v1beta1
metadata:
  name: cookbook-service
  namespace: jenkinsworld
spec:
  selector:
    app: cookbook
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000
  type: NodePort        
        
